"""rebuild

Revision ID: 2d49a6741933
Revises: e4b920e9e634
Create Date: 2019-07-31 19:42:09.069246

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2d49a6741933'
down_revision = 'e4b920e9e634'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
