"""add language to posts

Revision ID: e4227fda7255
Revises: 3b4ee8588c55
Create Date: 2019-07-30 05:36:45.562622

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e4227fda7255'
down_revision = '3b4ee8588c55'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('followers', 'followed_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('followers', 'follower_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('followers', 'follower_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('followers', 'followed_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
